### ISSUE TITLE
Boundary Event Shared Behaviour

### ISSUE THREAD

**Issue by tuantruong625** [ProcessMaker/modeler#581]
Create a base boundary event component with functionally that can be shared for all boundary event types.

We still have code from the first iteration of boundary events and will go through the requirements to see what is left to do and create separate issues for them.  

- [x] Drag on to task elements (task, manual task, script task, connector and call activity) (https://github.com/ProcessMaker/modeler/issues/589)
- [x] Reposition around the border of the element with 3 connection points per side (for a total of 12) (#593)
- [x] Crown for deleting boundary event
- [x] Crown for add flow elements (https://github.com/ProcessMaker/modeler/issues/590, https://github.com/ProcessMaker/modeler/issues/558)
- [x] Support for solid and dashed borders (addressed in #533)
- [x] Inspector config with name and icon ~that can be shared between boundary events~ (We'll do the second part of this when we have multiple types of boundary events). (@velkymx can we clarify with you what's needed on this?)
- [x] Can be moved between other tasks (https://github.com/ProcessMaker/modeler/issues/591)

[Boundary Event Shared Behaviors.pdf](https://github.com/ProcessMaker/modeler/files/3556295/Boundary.Event.Shared.Behaviors.pdf)

**Comment by chipit24** [comment]
From the PDF:
<img width="597" alt="Screen Shot 2019-09-03 at 10 55 26 AM" src="https://user-images.githubusercontent.com/7561061/64184369-5c639a80-ce39-11e9-8527-3caa1ed556be.png">

Though I think some things require clarification:
* Although all boundary events have an icon and a name, they will differ. I think the actionable item here is to create a single share boundary event inspector config.
* When dragging a  boundary event onto the grid, elements to which it cannot attach to should turn red (not sure if this was done in the 1st checkbox item).

**Comment by JCook21** [comment]
Closing this issue as all of the related tasks are complete.
